name: Dispatch
on: repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    name: my-job
    steps:
    - name: run hello
      run: echo "$HI"
      env:
        HI: ${{ toJson(github.event.client_payload) }}
